// Video B — horizontal 1920x1080 for LinkedIn / README. English.
import React from "react";
import { AbsoluteFill, Sequence, useCurrentFrame } from "remotion";
import conv from "../capture/bot/conversation.json";
import { Chat, ChannelPost, Entry, Notification, schedule } from "./chat";
import { Cta, Finding, Hook, Pipeline, Problem } from "./scenes";
import { C, FONT_EN, keys, sec } from "./theme";
import { Backdrop, Browser, Cap, Captions, Pop, Scene } from "./ui";

const chat = schedule(conv.conversation as Entry[], 12, 0.6);

export const HZ = {
  hook: 96,
  problem: 170,
  home: 200,
  banana: 400,
  onion: 110,
  dark: 75,
  bot: chat.end + 250,
  pipeline: 235,
  finding: 300,
  accuracy: 140,
  cta: 165,
};
const order = Object.keys(HZ) as (keyof typeof HZ)[];
export const HSTART = Object.fromEntries(
  order.map((k, i) => [k, order.slice(0, i).reduce((s, j) => s + HZ[j], 0)]),
) as Record<keyof typeof HZ, number>;
export const H_TOTAL = order.reduce((s, k) => s + HZ[k], 0);
const S = HSTART;
const ALERT_AT = chat.items.find((i) => i.text === "/alert നേന്ത്രൻ")!.typeFrom!;
const NOTIF = chat.end + 10; // inside the bot sequence
const CHANNEL = chat.end + 100;

const CAPS: Cap[] = [
  { from: 0, to: S.problem, en: "Kerala crop prices + a 7-day expected range — free, every morning" },
  { from: S.problem, to: S.home, en: "Farmers often sell without knowing which market pays more" },
  { from: S.home, to: S.banana, en: "17 crops: today's price, the change over a week, the best market" },
  { from: S.banana, to: S.banana + 170, en: "Price history with the 7-day expected range" },
  { from: S.banana + 170, to: S.banana + 280, en: "“Is this price high?” — this year vs last year vs the 5-year average" },
  { from: S.banana + 280, to: S.onion, en: "Every market, sortable, and a district map" },
  { from: S.onion, to: S.dark, en: "Same for small onion, tomato, coffee, arecanut…" },
  { from: S.dark, to: S.bot, en: "Light and dark, Malayalam and English, installable as an app" },
  { from: S.bot, to: S.bot + ALERT_AT, en: "The Telegram bot answers in Malayalam — typos are fine" },
  { from: S.bot + ALERT_AT, to: S.bot + chat.end, en: "Tap a market, set an alert, switch to English any time" },
  { from: S.bot + NOTIF, to: S.bot + CHANNEL, en: "Alerts fire on real prices, once per crossing" },
  { from: S.bot + CHANNEL, to: S.pipeline, en: "And one short post in the channel every morning" },
  { from: S.pipeline, to: S.finding, en: "A self-retraining MLOps pipeline on free tiers" },
  { from: S.finding, to: S.accuracy, en: "Honest metrics: a calibrated range instead of fake precision" },
  { from: S.accuracy, to: S.cta, en: "Live accuracy is published next to the naive baseline" },
  { from: S.cta, to: H_TOTAL, en: "Free for farmers and traders in Kerala" },
];

const BULLETS = [
  { at: 20, t: "Real replies, generated by the bot's own code against the live database" },
  { at: 150, t: "Crop names in Malayalam or English — typos OK" },
  { at: 250, t: "Market buttons → an alert in two taps" },
  { at: 380, t: "Every reply ends with the source and “not a guarantee”" },
];

const BotScene: React.FC = () => {
  const f = useCurrentFrame();
  const right = f < NOTIF ? "bullets" : f < CHANNEL ? "alert" : "channel";
  return (
    <AbsoluteFill>
      <div style={{ position: "absolute", left: 150, top: 32 }}>
        <Pop>
          <div style={{ padding: "10px 26px", borderRadius: 40, background: C.accent, color: "#fff", fontFamily: FONT_EN, fontWeight: 700, fontSize: 26 }}>
            Real replies from @keralacropprices_bot
          </div>
        </Pop>
      </div>
      <div style={{ position: "absolute", left: 150, top: 100 }}>
        <Chat items={chat.items} width={760} height={830} fs={24} title="കേരള വിപണി വില ബോട്ട്" />
      </div>
      <div style={{ position: "absolute", left: 1000, top: 100, width: 780, height: 830 }}>
        {right === "bullets" ? (
          <div style={{ display: "flex", flexDirection: "column", gap: 26, paddingTop: 120 }}>
            {BULLETS.map((b) =>
              f >= b.at ? (
                <Pop key={b.t} delay={b.at}>
                  <div style={{ display: "flex", gap: 20, alignItems: "flex-start" }}>
                    <div style={{ width: 16, height: 16, marginTop: 16, borderRadius: 8, background: C.accent, flex: "none" }} />
                    <div style={{ fontFamily: FONT_EN, fontSize: 38, fontWeight: 650, color: C.ink, lineHeight: 1.3 }}>{b.t}</div>
                  </div>
                </Pop>
              ) : null,
            )}
          </div>
        ) : right === "alert" ? (
          <div style={{ paddingTop: 200 }}>
            <Notification text={conv.alert_example.text} fs={27} width={780} delay={NOTIF + 4} />
          </div>
        ) : (
          <Pop delay={CHANNEL}>
            <ChannelPost text={conv.channel_post} width={780} height={830} fs={23} scroll={keys(f - CHANNEL, [[0, 0], [25, 0], [150, 1500]])} />
          </Pop>
        )}
      </div>
    </AbsoluteFill>
  );
};

const Site: React.FC<{ url: string; video?: string; from?: number; image?: string }> = ({ url, video, from = 0, image }) => (
  <AbsoluteFill style={{ alignItems: "center", paddingTop: 30 }}>
    <Browser url={url} width={1360} video={video} trimBefore={from} image={image} />
  </AbsoluteFill>
);

export const Horizontal: React.FC<{ sections: Record<string, number> }> = () => (
  <AbsoluteFill>
    <Backdrop />
    <Sequence durationInFrames={HZ.hook}>
      <Scene dur={HZ.hook}>
        <Hook v={false} />
      </Scene>
    </Sequence>
    <Sequence from={S.problem} durationInFrames={HZ.problem}>
      <Scene dur={HZ.problem}>
        <Problem v={false} />
      </Scene>
    </Sequence>
    <Sequence from={S.home} durationInFrames={HZ.home}>
      <Site url="kerala-crop-forecaster.vercel.app/en" video="web/rec/d-home.webm" from={sec(2.3)} />
    </Sequence>
    <Sequence from={S.banana} durationInFrames={HZ.banana}>
      <Site url="kerala-crop-forecaster.vercel.app/en/crop/banana" video="web/rec/d-banana.webm" from={sec(2.0)} />
    </Sequence>
    <Sequence from={S.onion} durationInFrames={HZ.onion}>
      <Site url="kerala-crop-forecaster.vercel.app/en/crop/small_onion" video="web/rec/d-small-onion.webm" from={sec(2.0)} />
    </Sequence>
    <Sequence from={S.dark} durationInFrames={HZ.dark}>
      <Site url="kerala-crop-forecaster.vercel.app/en/crop/banana" image="web/d-banana-dark.png" />
    </Sequence>
    <Sequence from={S.bot} durationInFrames={HZ.bot}>
      <Scene dur={HZ.bot}>
        <BotScene />
      </Scene>
    </Sequence>
    <Sequence from={S.pipeline} durationInFrames={HZ.pipeline}>
      <Scene dur={HZ.pipeline}>
        <Pipeline />
      </Scene>
    </Sequence>
    <Sequence from={S.finding} durationInFrames={HZ.finding}>
      <Scene dur={HZ.finding}>
        <Finding />
      </Scene>
    </Sequence>
    <Sequence from={S.accuracy} durationInFrames={HZ.accuracy}>
      <Site url="kerala-crop-forecaster.vercel.app/en/accuracy" video="web/rec/d-accuracy.webm" from={sec(1.6)} />
    </Sequence>
    <Sequence from={S.cta} durationInFrames={HZ.cta}>
      <Scene dur={HZ.cta + 12}>
        <Cta v={false} />
      </Scene>
    </Sequence>
    <Captions caps={CAPS} layout="horizontal" />
  </AbsoluteFill>
);
