// Video B — horizontal 1920x1080 for LinkedIn / README. English. Cuts sit on the 18-frame beat
// grid; camera moves and seams come from motion.tsx (video-shotcraft shot cards).
import React from "react";
import { AbsoluteFill, Freeze, Sequence, useCurrentFrame } from "remotion";
import conv from "../capture/bot/conversation.json";
import { Chat, ChannelPost, Entry, Notification, schedule } from "./chat";
import { Annotate, ChapterCard, Crane, FlashCut, OVERLAP, Shot, b } from "./motion";
import { Cta, Finding, Hook, Pipeline, Problem } from "./scenes";
import { C, FONT_EN, keys, sec } from "./theme";
import { Backdrop, Browser, Cap, Captions, Pop, Scene } from "./ui";

const chat = schedule(conv.conversation as Entry[], 12, 0.55);
const ALERT_AT = chat.items.find((i) => i.text === "/alert നേന്ത്രൻ")!.typeFrom!;
const ceilBeat = (n: number) => Math.ceil(n / 18) * 18;

// Browser geometry (output px): 1360 px wide = 1440 CSS px of the recordings.
const BW = 1360;
const BS = BW / 1440;
const BX = (1920 - BW) / 2;
const BY = 30 + 58; // content top (below the address bar)
const out = (x: number, y: number) => ({ x: BX + x * BS, y: BY + y * BS });

// d-home.webm: the scroll reaches the banana cards at ~5.1 s and rests until 6.7 s
const HOME_FROM = sec(2.3);
const FREEZE_AT = sec(6.0);
const PLAY1 = FREEZE_AT - HOME_FROM;
const FREEZE = b(3);
// "Best market today: Parassala ₹70" on the Nendran card, in recording px at the freeze
const BEST = { x: 384, y: 360, w: 286, h: 39 };

export const HZ = {
  hook: b(6),
  problem: b(8),
  crane: b(6),
  home: b(15),
  banana: b(18),
  onion: b(7),
  dark: b(4),
  chapterBot: b(3),
  bot: ceilBeat(chat.end + 230),
  chapterHow: b(3),
  pipeline: b(12),
  finding: b(15),
  accuracy: b(6),
  cta: b(9),
};
const order = Object.keys(HZ) as (keyof typeof HZ)[];
export const HSTART = Object.fromEntries(
  order.map((k, i) => [k, order.slice(0, i).reduce((s, j) => s + HZ[j], 0)]),
) as Record<keyof typeof HZ, number>;
export const H_TOTAL = order.reduce((s, k) => s + HZ[k], 0);
const S = HSTART;
const NOTIF = chat.end + 10; // inside the bot sequence
const CHANNEL = chat.end + 96;

const CAPS: Cap[] = [
  { from: 0, to: S.problem, en: "Kerala crop prices + a 7-day expected range — free" },
  { from: S.problem, to: S.crane, en: "Farmers often sell without knowing which market pays more" },
  { from: S.crane, to: S.home + PLAY1, en: "17 crops: today's price and the change over a week" },
  { from: S.home + PLAY1, to: S.banana, en: "…and the market paying the most today" },
  { from: S.banana, to: S.banana + 170, en: "Price history with the 7-day expected range" },
  { from: S.banana + 170, to: S.onion, en: "“Is this price high?” — vs last year and the 5-year average" },
  { from: S.onion, to: S.dark, en: "Same for small onion, tomato, coffee, arecanut…" },
  { from: S.dark, to: S.chapterBot, en: "Light and dark, Malayalam and English, installable" },
  { from: S.bot, to: S.bot + ALERT_AT, en: "The Telegram bot answers in Malayalam — typos are fine" },
  { from: S.bot + ALERT_AT, to: S.bot + NOTIF, en: "Tap a market, set an alert, switch to English any time" },
  { from: S.bot + NOTIF, to: S.bot + CHANNEL, en: "Alerts fire on real prices, once per crossing" },
  { from: S.bot + CHANNEL, to: S.chapterHow, en: "And one short post in the channel every morning" },
  { from: S.pipeline, to: S.finding, en: "A self-retraining MLOps pipeline on free tiers" },
  { from: S.finding, to: S.accuracy, en: "Honest metrics: a calibrated range, not fake precision" },
  { from: S.accuracy, to: S.cta, en: "Live accuracy, published next to the naive baseline" },
  { from: S.cta, to: H_TOTAL, en: "Free for farmers and traders in Kerala" },
];

const BULLETS = [
  { at: 20, t: "Real replies, generated by the bot's own code against the live database" },
  { at: 150, t: "Crop names in Malayalam or English — typos OK" },
  { at: 250, t: "Market buttons → an alert in two taps" },
  { at: 370, t: "Every reply ends with the source and “not a guarantee”" },
];

const BotScene: React.FC = () => {
  const f = useCurrentFrame();
  const right = f < NOTIF ? "bullets" : f < CHANNEL ? "alert" : "channel";
  return (
    <AbsoluteFill>
      <div style={{ position: "absolute", left: 150, top: 28 }}>
        <Pop>
          <div style={{ padding: "10px 26px", borderRadius: 40, background: C.accent, color: "#fff", fontFamily: FONT_EN, fontWeight: 700, fontSize: 28 }}>
            Real replies from @keralacropprices_bot
          </div>
        </Pop>
      </div>
      <div style={{ position: "absolute", left: 150, top: 96 }}>
        <Chat items={chat.items} width={760} height={830} fs={24} title="കേരള വിപണി വില ബോട്ട്" />
      </div>
      <div style={{ position: "absolute", left: 1000, top: 96, width: 780, height: 830 }}>
        {right === "bullets" ? (
          <div style={{ display: "flex", flexDirection: "column", gap: 26, paddingTop: 110 }}>
            {BULLETS.map((x) =>
              f >= x.at ? (
                <Pop key={x.t} delay={x.at}>
                  <div style={{ display: "flex", gap: 20, alignItems: "flex-start" }}>
                    <div style={{ width: 16, height: 16, marginTop: 18, borderRadius: 8, background: C.accent, flex: "none" }} />
                    <div style={{ fontFamily: FONT_EN, fontSize: 40, fontWeight: 650, color: C.ink, lineHeight: 1.28 }}>{x.t}</div>
                  </div>
                </Pop>
              ) : null,
            )}
          </div>
        ) : right === "alert" ? (
          <div style={{ paddingTop: 200 }}>
            <Notification text={conv.alert_example.text} fs={28} width={780} delay={NOTIF + 4} />
          </div>
        ) : (
          <Pop delay={CHANNEL}>
            <ChannelPost text={conv.channel_post} width={780} height={830} fs={23} scroll={keys(f - CHANNEL, [[0, 0], [24, 0], [HZ.bot - CHANNEL - 14, 1500]])} />
          </Pop>
        )}
      </div>
    </AbsoluteFill>
  );
};

const Site: React.FC<{ url: string; video?: string; from?: number; image?: string }> = ({ url, video, from = 0, image }) => (
  <AbsoluteFill style={{ alignItems: "center", paddingTop: 30 }}>
    <Browser url={url} width={BW} video={video} trimBefore={from} image={image} />
  </AbsoluteFill>
);

/** Home: real recording; freezes on the banana cards while the best market is circled
 * (speed-ramp-freeze · freeze-annotate), then plays on. */
const HomeShot: React.FC = () => {
  const c = out(BEST.x, BEST.y);
  const url = "kerala-crop-forecaster.vercel.app/en";
  return (
    <>
      <Sequence durationInFrames={PLAY1}>
        <Site url={url} video="web/rec/d-home.webm" from={HOME_FROM} />
      </Sequence>
      <Sequence from={PLAY1} durationInFrames={FREEZE}>
        <Freeze frame={PLAY1 - 1}>
          <Site url={url} video="web/rec/d-home.webm" from={HOME_FROM} />
        </Freeze>
        <Annotate cx={c.x} cy={c.y} rx={(BEST.w / 2) * BS + 30} ry={(BEST.h / 2) * BS + 22} dur={FREEZE} width={1920} height={1080} stroke={7} />
      </Sequence>
      <Sequence from={PLAY1 + FREEZE}>
        <Site url={url} video="web/rec/d-home.webm" from={FREEZE_AT} />
      </Sequence>
    </>
  );
};

export const Horizontal: React.FC<{ sections: Record<string, number> }> = () => (
  <AbsoluteFill>
    <Backdrop />
    <Sequence durationInFrames={HZ.hook}>
      <Scene dur={HZ.hook}>
        <Hook v={false} />
      </Scene>
    </Sequence>
    <Sequence from={S.problem} durationInFrames={HZ.problem}>
      <Scene dur={HZ.problem}>
        <Problem v={false} />
      </Scene>
    </Sequence>
    {/* crane-rise from one real price to the whole page; ends on the recording's first frame */}
    <Sequence from={S.crane} durationInFrames={HZ.crane}>
      <Shot dur={HZ.crane} width={1920} enter="fade">
        <Crane focal={out(274, 328)} center={{ x: 960, y: 540 }} zoom={2.0} hold={20} move={70}>
          <Site url="kerala-crop-forecaster.vercel.app/en" image="web/d-home-light.png" />
        </Crane>
      </Shot>
    </Sequence>
    <Sequence from={S.home} durationInFrames={HZ.home}>
      <Shot dur={HZ.home} width={1920} exit="focus">
        <HomeShot />
      </Shot>
    </Sequence>
    <Sequence from={S.banana - OVERLAP.focus} durationInFrames={HZ.banana + OVERLAP.focus}>
      <Shot dur={HZ.banana + OVERLAP.focus} width={1920} enter="focus" exit="whip">
        <Site url="kerala-crop-forecaster.vercel.app/en/crop/banana" video="web/rec/d-banana.webm" from={sec(2.0) - OVERLAP.focus} />
      </Shot>
    </Sequence>
    <Sequence from={S.onion - OVERLAP.whip} durationInFrames={HZ.onion + OVERLAP.whip}>
      <Shot dur={HZ.onion + OVERLAP.whip} width={1920} enter="whip">
        <Site url="kerala-crop-forecaster.vercel.app/en/crop/small_onion" video="web/rec/d-small-onion.webm" from={sec(2.0)} />
      </Shot>
    </Sequence>
    <Sequence from={S.dark} durationInFrames={HZ.dark}>
      <Shot dur={HZ.dark} width={1920} exit="fade">
        <Site url="kerala-crop-forecaster.vercel.app/en/crop/banana" image="web/d-banana-dark.png" />
      </Shot>
    </Sequence>
    <FlashCut at={S.dark} />
    <Sequence from={S.chapterBot} durationInFrames={HZ.chapterBot}>
      <ChapterCard dur={HZ.chapterBot} title="Telegram bot" sub="@keralacropprices_bot" size={84} />
    </Sequence>
    <Sequence from={S.bot} durationInFrames={HZ.bot}>
      <Scene dur={HZ.bot}>
        <BotScene />
      </Scene>
    </Sequence>
    <Sequence from={S.chapterHow} durationInFrames={HZ.chapterHow}>
      <ChapterCard dur={HZ.chapterHow} title="How it works" sub="MLOps on free tiers · ₹0" size={84} />
    </Sequence>
    <Sequence from={S.pipeline} durationInFrames={HZ.pipeline}>
      <Scene dur={HZ.pipeline}>
        <Pipeline title={false} />
      </Scene>
    </Sequence>
    <Sequence from={S.finding} durationInFrames={HZ.finding}>
      <Scene dur={HZ.finding}>
        <Finding />
      </Scene>
    </Sequence>
    <Sequence from={S.accuracy} durationInFrames={HZ.accuracy}>
      <Shot dur={HZ.accuracy} width={1920} enter="fade" exit="fade">
        <Site url="kerala-crop-forecaster.vercel.app/en/accuracy" video="web/rec/d-accuracy.webm" from={sec(1.6)} />
      </Shot>
    </Sequence>
    <Sequence from={S.cta} durationInFrames={HZ.cta}>
      <Scene dur={HZ.cta + 12}>
        <Cta v={false} />
      </Scene>
    </Sequence>
    <Captions caps={CAPS} layout="horizontal" />
  </AbsoluteFill>
);
